from django.conf import settings
from django.db import models


class Ad(models.Model):
    title = ...
    price = ...
    description = ...
    author = ...
    created_at = ...


class Comment(models.Model):
    text = ...
    author = ...
    ad = ...
    created_at = ...
